// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDxU56SV581em_cd83VzJkXuxkeMf8fUM',
    appId: '1:847075322554:web:bcab515f6ea4c82331b083',
    messagingSenderId: '847075322554',
    projectId: 'e-commerce-79990',
    authDomain: 'e-commerce-79990.firebaseapp.com',
    storageBucket: 'e-commerce-79990.firebasestorage.app',
    measurementId: 'G-X3MVF6MFV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdlCqyloXjHUiw-Pk8WiL2FX_29GNwd-I',
    appId: '1:847075322554:android:22277b5a544bea0731b083',
    messagingSenderId: '847075322554',
    projectId: 'e-commerce-79990',
    storageBucket: 'e-commerce-79990.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-TjE_oNwx26zhF5yBqMIZ0It9cIcQ4p4',
    appId: '1:847075322554:ios:1f89c7090782f95d31b083',
    messagingSenderId: '847075322554',
    projectId: 'e-commerce-79990',
    storageBucket: 'e-commerce-79990.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-TjE_oNwx26zhF5yBqMIZ0It9cIcQ4p4',
    appId: '1:847075322554:ios:1f89c7090782f95d31b083',
    messagingSenderId: '847075322554',
    projectId: 'e-commerce-79990',
    storageBucket: 'e-commerce-79990.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDxU56SV581em_cd83VzJkXuxkeMf8fUM',
    appId: '1:847075322554:web:329f166241d5d92531b083',
    messagingSenderId: '847075322554',
    projectId: 'e-commerce-79990',
    authDomain: 'e-commerce-79990.firebaseapp.com',
    storageBucket: 'e-commerce-79990.firebasestorage.app',
    measurementId: 'G-J79M2NQLBH',
  );
}
